server:
  port: 9000
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_security
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
